-- Seed initial skills (Master List of 300+ Real-World Student Skills, Roles, Frameworks & Interview Terms)
INSERT INTO skills (name) VALUES
-- 1. Web, App & Software Roles & Fields
('Web Development'),
('Front-End Development'),
('Back-End Development'),
('Full-Stack Development'),
('Software Engineering'),
('Mobile App Development'),
('iOS Development'),
('Android Development'),
('Cross-Platform Development'),
('DevOps Engineering'),
('Cloud Engineering'),
('Cybersecurity'),
('Game Development'),
('Data Engineering'),
('AI & Machine Learning Engineering'),
('QA & Test Automation Engineering'),

-- 2. Programming Languages
('JavaScript'),
('TypeScript'),
('Python'),
('Java'),
('C++'),
('C'),
('C#'),
('Go (Golang)'),
('Rust'),
('Swift'),
('Kotlin'),
('PHP'),
('Ruby'),
('Dart'),
('SQL'),
('HTML5'),
('CSS3'),
('Bash / Shell Scripting'),
('R'),
('MATLAB'),
('Scala'),

-- 3. Front-End Frameworks, Libraries & Tools
('React.js'),
('Next.js'),
('Vue.js'),
('Angular'),
('Svelte'),
('Tailwind CSS'),
('Bootstrap'),
('Material UI'),
('Redux'),
('Zustand'),
('Sass / SCSS'),
('Vite'),
('Webpack'),
('Single Page Applications (SPA)'),
('Progressive Web Apps (PWA)'),

-- 4. Back-End Frameworks, Runtimes & APIs
('Node.js'),
('Express.js'),
('NestJS'),
('Django'),
('Flask'),
('FastAPI'),
('Spring Boot'),
('Ruby on Rails'),
('ASP.NET Core'),
('Laravel'),
('GraphQL'),
('RESTful APIs'),
('gRPC'),
('WebSockets & Socket.io'),
('Microservices Architecture'),
('Serverless Architecture'),
('ORM (Prisma / Sequelize / Hibernate)'),

-- 5. Databases, Cloud, Infrastructure & Security
('PostgreSQL'),
('MongoDB'),
('MySQL'),
('Redis'),
('Firebase'),
('Supabase'),
('SQLite'),
('Oracle DB'),
('Cassandra'),
('AWS (Amazon Web Services)'),
('Google Cloud Platform (GCP)'),
('Microsoft Azure'),
('Docker'),
('Kubernetes'),
('CI/CD Pipelines'),
('GitHub Actions'),
('Terraform'),
('Nginx'),
('Linux System Administration'),
('Ethical Hacking'),
('Network Security'),
('JWT & OAuth Authentication'),

-- 6. AI, Data Science & Machine Learning
('Machine Learning'),
('Deep Learning'),
('Artificial Intelligence'),
('Generative AI'),
('Large Language Models (LLMs)'),
('Prompt Engineering'),
('Natural Language Processing (NLP)'),
('Computer Vision'),
('TensorFlow'),
('PyTorch'),
('Scikit-Learn'),
('Pandas & NumPy'),
('OpenCV'),
('Keras'),
('LangChain'),
('Hugging Face'),
('Data Analysis'),
('Data Visualization'),
('Data Mining'),
('Big Data'),
('Microsoft Power BI'),
('Tableau'),

-- 7. Core Computer Science & Interview Preparation
('Data Structures & Algorithms (DSA)'),
('System Design'),
('Object-Oriented Programming (OOP)'),
('Database Management Systems (DBMS)'),
('Operating Systems (OS)'),
('Computer Networks (CN)'),
('Competitive Programming'),
('Quantitative Aptitude'),
('Logical Reasoning'),
('Verbal Ability & Comprehension'),
('Case Study Analysis'),
('Behavioral Interviewing (STAR Method)'),
('Guesstimates & Estimation'),
('Mock Interviews'),
('Git & GitHub Version Control'),
('Unit Testing & Test-Driven Development (TDD)'),
('Code Review'),

-- 8. Engineering Branches (Mechanical, Electrical, Civil, ECE, EEE, Robotics)
('AutoCAD'),
('SolidWorks'),
('Ansys'),
('LabVIEW'),
('Circuit Design'),
('PCB Design'),
('Embedded Systems'),
('Microcontrollers (Arduino / Raspberry Pi)'),
('Robotics'),
('Mechatronics'),
('PLC & SCADA Programming'),
('3D Printing & Rapid Prototyping'),
('Mechanical Design'),
('Civil Engineering Design'),
('Structural Engineering'),
('Geotechnical Engineering'),
('Surveying & Mapping'),
('Thermodynamics'),
('Fluid Mechanics'),
('VLSI Design'),
('Verilog / VHDL'),
('Signal Processing'),
('Power Systems Engineering'),
('PSpice & Circuit Simulation'),
('Quality Assurance & Quality Control (QA/QC)'),
('Site Engineering'),

-- 9. Design, UI/UX, Product & Multimedia
('UI/UX Design'),
('Figma'),
('Adobe XD'),
('User Research'),
('Wireframing & Prototyping'),
('Graphic Design'),
('Adobe Photoshop'),
('Adobe Illustrator'),
('Adobe Premiere Pro'),
('Adobe After Effects'),
('Video Editing'),
('Motion Graphics'),
('3D Modeling'),
('Blender'),
('Canva'),
('Game Engine (Unity / Unreal Engine)'),
('Storyboarding'),
('Fashion Design'),
('Interior Design'),

-- 10. Business, Management, Finance & Marketing
('Product Management'),
('Project Management'),
('Agile & Scrum Methodologies'),
('Business Analysis'),
('Financial Modeling'),
('Financial Analysis & Valuation (DCF)'),
('Accounting'),
('Corporate Finance'),
('Investment Banking'),
('Digital Marketing'),
('SEO & SEM'),
('Social Media Marketing'),
('Content Marketing'),
('Brand Strategy'),
('Sales & Negotiation'),
('Business Development'),
('Public Speaking'),
('Entrepreneurship'),
('Supply Chain & Logistics'),
('Human Resource Management (HRM)'),
('Event Management'),
('Customer Relationship Management (CRM)'),
('Market Research'),
('SWOT & PESTLE Analysis'),
('Growth Hacking'),
('Customer Journey Mapping'),
('Statutory Auditing'),
('Tax Planning'),

-- 11. Healthcare, Medicine, Biotech & Life Sciences
('Clinical Research'),
('Clinical Diagnostics'),
('Patient Care & Nursing'),
('Medical Terminology'),
('Anatomy & Physiology'),
('Laboratory Research'),
('Pharmacology'),
('Biotechnology'),
('Bioinformatics'),
('Molecular Biology'),
('Biochemistry'),
('Genetics'),
('Immunology'),
('Public Health'),
('Microbiology'),
('Histology'),
('First Aid & CPR'),
('Biomedical Equipment Operation'),
('Clinical Trial Protocols'),
('Good Manufacturing Practices (GMP)'),
('Regulatory Compliance (FDA / EMA)'),

-- 12. Law, Humanities, Social Sciences & Languages
('Legal Research'),
('Legal Writing'),
('Contract Drafting'),
('Mooting & Litigation'),
('International Law'),
('Public Policy'),
('Political Analysis'),
('Technical Writing'),
('Content Writing'),
('Academic Research'),
('Public Relations (PR)'),
('Debating & Pitching'),
('Copywriting'),
('Creative Writing'),
('Translation'),
('Foreign Languages'),
('Philosophy & Logic'),
('Sociology & Social Work'),
('Journalism'),
('Psychology & Counseling'),
('Intellectual Property & Patent Drafting'),

-- 13. Essential Workplace & Professional Soft Skills
('Problem Solving'),
('Time Management'),
('Critical Thinking'),
('Cross-Functional Collaboration'),
('Conflict Resolution'),
('Adaptability & Resilience'),
('Stakeholder Management'),
('Emotional Intelligence (EQ)'),
('Strategic Communication'),
('Corporate Etiquette'),
('Leadership & Mentorship'),
('Notion Workspace Management'),
('JIRA & Confluence'),
('Slack & Team Communication'),
('Trello')
ON CONFLICT (name) DO NOTHING;

-- Seed initial interests (Comprehensive Multi-Disciplinary Areas of Interest for All Branches)
INSERT INTO interests (name) VALUES
-- 1. Web, App & Software Development
('Web Development'),
('Front-End Development'),
('Back-End Development'),
('Full-Stack Development'),
('Mobile App Development'),
('DevOps & Infrastructure'),
('Cloud Computing'),
('Cybersecurity & Ethical Hacking'),
('Game Development'),
('Open Source Projects'),
('Hackathons & Coding Contests'),
('Competitive Programming'),

-- 2. Artificial Intelligence, Data Science & Tech
('Artificial Intelligence (AI)'),
('Machine Learning & Deep Learning'),
('Generative AI & LLMs'),
('Data Science & Analytics'),
('Robotics & Automation'),
('Blockchain & Web3'),
('IoT & Smart Hardware'),
('AR / VR & Spatial Computing'),
('System Architecture'),

-- 3. Design, Creative & Media
('UI/UX & Product Design'),
('Graphic Design & Branding'),
('Content Creation & Vlogging'),
('Video Editing & Motion Graphics'),
('3D Modeling & Animation'),
('Game Art & Design'),
('Photography & Cinematography'),
('Fashion & Textile Design'),
('Architecture & Spatial Design'),

-- 4. Business, Entrepreneurship & Product
('Startups & Venture Capital'),
('Product Management'),
('Finance & Fintech'),
('Stock Market & Trading'),
('Digital Marketing & Growth'),
('E-commerce & D2C Brands'),
('Social Entrepreneurship'),
('Consulting & Strategy'),
('Real Estate & Investment'),

-- 5. Core Engineering Branches
('Mechanical Engineering & Automotive'),
('Electrical & Power Systems'),
('Electronics & Circuit Design'),
('Civil Engineering & Infrastructure'),
('Aerospace & Aviation'),
('Renewable Energy & Climate Tech'),

-- 6. Healthcare, Medicine & Sciences
('Biotechnology & MedTech'),
('Healthcare & Clinical Research'),
('Pharmaceuticals & Drug Discovery'),
('Genetics & Genomics'),
('Neuroscience & Mental Health'),
('Environmental Science & Sustainability'),

-- 7. Law, Humanities, Social & Education
('Law, Policy & Governance'),
('International Relations'),
('Journalism & Media Production'),
('Academic Research & Publishing'),
('Social Work & Community Impact'),
('Education & EdTech'),
('Creative Writing & Blogging')
ON CONFLICT (name) DO NOTHING;
